name: Workflow tests
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Planemo
        run: pip install planemo
      - name: Run workflow tests
        run: planemo test interactive-desktop-workflow.xml
